apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o deployment.yml
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: blog
      name: blog
      namespace: proxytunnel
    spec:
      ports:
        - name: "3128"
          port: 3128
          targetPort: 3128
      selector:
        io.kompose.service: blog
    status:
      loadBalancer: {}
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o deployment.yml
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: blog
      name: blog
      namespace: proxytunnel
    spec:
      replicas: 1
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose.yml -o deployment.yml
            kompose.version: 1.20.0 ()
          creationTimestamp: null
          labels:
            io.kompose.service: blog
        spec:
          containers:
            - image: germey/proxytunnel
              name: blog
              ports:
              env:
                - name: PEERS_CONF
                  valueFrom:
                    configMapKeyRef:
                      name: squid
                      key: "peers.conf"
                - name: SQUID_CONF
                  valueFrom:
                    configMapKeyRef:
                      name: squid
                      key: "squid.conf"
                - containerPort: 3128
              resources: {}
          restartPolicy: Always
    status: {}
kind: List
metadata: {}

