version: '3.1'

services:
  proxytunnel:
    image: germey/proxytunnel
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3128:3128'
    environment:
      PEERS_CONF: "# test"
